◯　行列

◯　行列の足し算と引き算をPythonで実行

In [2]:
import numpy as np

# 行列A
A = np.matrix([[50,40],[10,10]])
# 行列B
B = np.matrix([[30,100],[10,15]])

# A + B
A + B

matrix([[ 80, 140],
        [ 20,  25]])

◯　行列の実数倍を求める

In [4]:
# 先ほどの結果の８割の数字を求める場合
import numpy as np

# 行列A
A = np.matrix([[80, 140],[20,25]])
# 0.8 × A
0.8 * A

matrix([[ 64., 112.],
        [ 16.,  20.]])

◯　行列の掛け算を実行

In [6]:
import numpy as np
# 行列A（掛けられる側）
A = np.matrix([[1,3],[2,1]])
# 行列B（掛ける側）
B = np.matrix([[150,250],[130,230]])
# A * B
A * B

matrix([[540, 940],
        [430, 730]])

◯　l×m行列とm×n行列の掛け算

In [1]:
# 掛ける順番に注意
import numpy as np

# 行列A（２×２行列）
A = np.matrix([[1,3],[2,1]])
# 行列B（２×１行列）
B = np.matrix([[145],[72]])
# A×Bを計算
A * B

matrix([[361],
        [362]])

◯　単位行列

◯　行列×単位行列を計算する

# 片方の行列が単位行列のときは掛け算でも交換法則が成立
import numpy as np

# 行列A
A = np.matrix([[1,3],[2,1]])
# 単位行列E
E = np.matrix([[1,0],[0,1]])
# A×E
A * E

In [3]:
# E×A
E * A

matrix([[1, 3],
        [2, 1]])

◯逆行列を求める

In [5]:
# AB = BA = E が成立するとき、行列Bは行列Aの逆行列となる
# Numpyのlinalg.inv()関数で逆行列が求められる
import numpy as np

# 行列A
A = np.matrix([[5,3],[2,1]])
# 逆行列を求める
B = np.linalg.inv(A)

B

matrix([[-1.,  3.],
        [ 2., -5.]])

◯　単位行列になることを確認

In [8]:
(A * B).astype(np.int64)

matrix([[1, 0],
        [0, 0]])

◯　逆行列で連立方程式を解く

In [9]:
# 5x + 3y = 9
# 2x + y = 4

import numpy as np

# 行列A
A = np.matrix([[5,3],[2,1]])
# 行列Aの逆行列
inv_A = np.linalg.inv(A)
# 行列B
B = np.matrix([[9],[4]])
# 逆行列×行列B
inv_A * B

matrix([[ 3.],
        [-2.]])